/**
 * ReportExport Component
 * Export reports with working PDF download
 */

import { Download, FileText } from 'lucide-react';

export default function ReportExport({ reportData, projectName, reportText }) {
  const exportToPDF = () => {
    if (!reportText) {
      alert('No report to export. Generate a report first!');
      return;
    }

    // Create a printable HTML version
    const printWindow = window.open('', '_blank');
    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>${projectName} - Status Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
      color: #333;
    }
    h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #1e40af; margin-top: 30px; }
    h3 { color: #1e3a8a; }
    table { border-collapse: collapse; width: 100%; margin: 20px 0; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
    th { background-color: #f3f4f6; font-weight: bold; }
    .header { text-align: center; margin-bottom: 40px; }
    .footer { margin-top: 40px; text-align: center; color: #666; font-size: 12px; }
    @media print {
      body { margin: 0; padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Project Management Report</h1>
    <p>Generated on ${new Date().toLocaleDateString()}</p>
  </div>
  <div>${reportText.replace(/\n/g, '<br>').replace(/^# /gm, '<h1>').replace(/^## /gm, '<h2>').replace(/^### /gm, '<h3>')}</div>
  <div class="footer">
    <p>Generated by PM Agent - Project Management System</p>
    <p>${new Date().toLocaleString()}</p>
  </div>
  <div class="no-print" style="margin-top: 20px; text-align: center;">
    <button onclick="window.print()" style="padding: 10px 20px; background: #2563eb; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 16px;">Print / Save as PDF</button>
    <button onclick="window.close()" style="margin-left: 10px; padding: 10px 20px; background: #6b7280; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 16px;">Close</button>
  </div>
</body>
</html>
    `;
    
    printWindow.document.write(html);
    printWindow.document.close();
  };

  const exportToMarkdown = () => {
    if (!reportText) {
      alert('No report to export. Generate a report first!');
      return;
    }
    
    const blob = new Blob([reportText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName}-report-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportToText = () => {
    if (!reportText) {
      alert('No report to export. Generate a report first!');
      return;
    }
    
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName}-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={styles.container}>
      <h3 style={styles.title}>Export Report</h3>
      
      <div style={styles.options}>
        <button onClick={exportToPDF} style={styles.exportButton}>
          <Download size={20} />
          <div>
            <div style={styles.buttonTitle}>Export as PDF</div>
            <div style={styles.buttonDesc}>Print-friendly PDF format</div>
          </div>
        </button>

        <button onClick={exportToMarkdown} style={styles.exportButton}>
          <FileText size={20} />
          <div>
            <div style={styles.buttonTitle}>Download Markdown</div>
            <div style={styles.buttonDesc}>Markdown (.md) file</div>
          </div>
        </button>

        <button onClick={exportToText} style={styles.exportButton}>
          <FileText size={20} />
          <div>
            <div style={styles.buttonTitle}>Download Text</div>
            <div style={styles.buttonDesc}>Plain text (.txt) file</div>
          </div>
        </button>
      </div>
    </div>
  );
}

const styles = {
  container: {
    backgroundColor: '#0a0a0a',
    border: '1px solid #2a2a2a',
    borderRadius: '12px',
    padding: '2rem',
    marginTop: '2rem',
  },
  title: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '1.5rem',
  },
  options: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1rem',
  },
  exportButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1.25rem',
    backgroundColor: '#141414',
    border: '1px solid #2a2a2a',
    borderRadius: '8px',
    color: '#ffffff',
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'left',
  },
  buttonTitle: {
    fontSize: '0.9375rem',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '0.25rem',
  },
  buttonDesc: {
    fontSize: '0.75rem',
    color: '#a0a0a0',
  },
};