

import { Download, FileText, FileSpreadsheet, Mail } from 'lucide-react';

export default function ReportExport({ reportData, projectName }) {
  const exportToPDF = () => {
   
    console.log('Exporting to PDF...');
    alert('PDF export functionality - integrate jsPDF library');
  };

  const exportToMarkdown = () => {
    if (!reportData) return;
    
    const markdown = generateMarkdown(reportData, projectName);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName}-report-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const exportToCSV = () => {
    if (!reportData) return;
    
    const csv = generateCSV(reportData);
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName}-data-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeURLObjectURL(url);
  };

  const sendViaEmail = () => {
    if (!reportData) return;
    
    const subject = `Project Report: ${projectName}`;
    const body = `Please find the project report attached.\n\nGenerated on: ${new Date().toLocaleDateString()}`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div style={styles.container}>
      <h3 style={styles.title}>Export Report</h3>
      
      <div style={styles.options}>
        <button onClick={exportToPDF} style={styles.exportButton}>
          <FileText size={20} />
          <div>
            <div style={styles.buttonTitle}>Export as PDF</div>
            <div style={styles.buttonDesc}>Professional PDF document</div>
          </div>
        </button>

        <button onClick={exportToMarkdown} style={styles.exportButton}>
          <FileText size={20} />
          <div>
            <div style={styles.buttonTitle}>Export as Markdown</div>
            <div style={styles.buttonDesc}>Plain text format</div>
          </div>
        </button>

        <button onClick={exportToCSV} style={styles.exportButton}>
          <FileSpreadsheet size={20} />
          <div>
            <div style={styles.buttonTitle}>Export as CSV</div>
            <div style={styles.buttonDesc}>Spreadsheet data</div>
          </div>
        </button>

        <button onClick={sendViaEmail} style={styles.exportButton}>
          <Mail size={20} />
          <div>
            <div style={styles.buttonTitle}>Send via Email</div>
            <div style={styles.buttonDesc}>Share with team</div>
          </div>
        </button>
      </div>
    </div>
  );
}

function generateMarkdown(reportData, projectName) {
  return `# Project Report: ${projectName}

**Generated on:** ${new Date().toLocaleDateString()}

## Executive Summary

${reportData.report || 'No report data available'}

## Key Metrics

- **Completion:** ${reportData.completion_percentage || 0}%
- **Status:** ${reportData.status || 'Active'}
- **Health:** ${reportData.health_indicator || 'N/A'}

---

*Generated by Project Management Agent*
`;
}

function generateCSV(reportData) {
  return `Metric,Value
Project Name,${reportData.name || 'N/A'}
Completion,${reportData.completion_percentage || 0}%
Status,${reportData.status || 'N/A'}
Generated,${new Date().toISOString()}
`;
}

const styles = {
  container: {
    backgroundColor: '#0a0a0a',
    border: '1px solid #2a2a2a',
    borderRadius: '12px',
    padding: '2rem',
    marginTop: '2rem',
  },
  title: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '1.5rem',
  },
  options: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1rem',
  },
  exportButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1.25rem',
    backgroundColor: '#141414',
    border: '1px solid #2a2a2a',
    borderRadius: '8px',
    color: '#ffffff',
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'left',
  },
  buttonTitle: {
    fontSize: '0.9375rem',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '0.25rem',
  },
  buttonDesc: {
    fontSize: '0.75rem',
    color: '#a0a0a0',
  },
};